spring.application.name=Ecommerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce

spring.datasource.username=root

spring.datasource.password=Perumal@27

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

cloudinary.cloud-name=vzninrsa
cloudinary.api-key=432195343945194
cloudinary.api-secret=XQ9Pd-brymB_WKRgfg2jkOnh898

jwt.secret=MySuperSecretKeyForEcommerceApplication123456789012345678

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

razorpay.key.id=rzp_test_TalJYq1DISqsGe


razorpay.key.secret=yTtGi38XHn02Lx2tRgMLzktj

